### PR TITLE
Asign module name defined in .env file.

### PR DESCRIPTION
**Pull request by pabloarias**

### CODE REVIEW

**Comment by carcam** [comment]
The variable [EXTENSION_NAME] can have spaces and will then not allow for translation in the platform. The current naming is clear enough as it will create: _mod_extensionalias_ and it's perfect for projects of just one module.

In my opinino this should not be merged as it breaks localization of the modules.

**Comment by pabloarias** [comment]
Hello, Carlos, thanks for your answer.

We are talking about module name. Yes, this name can have spaces and that's right.

For example, I think mod_article_latest is not a good name. Latest Articles is the right name.

If someone wants to translate module name, I think it can be achieved by filling this variable with a translatable constant.

Just opinions, Aníbal will decide.

**Comment by carcam** [comment]
I agree it's an aweful name, but it will be even worst not being able to translate it ;)

If yoy use that specific variable the name of the module will not be translatable on most scenarios.

**Comment by anibalsanchez** [comment]
The idea of the build files is creating a good starting point. In this case, I think ´<name>mod_[EXTENSION_ALIAS]</name>´ is better initial value since it facilitates and promotes translations.

`<name>[EXTENSION_NAME]</name>` is not bad at all. Many extensions have the name there. In fact, when I don't plan to translate an extension I write the string right there.

To keep consistency with the rest of the XML files, I opt to follow the convention that supports translations.

Thank you @pabloarias for your PR!

**Pull request closed without merging**
